const
  BMP_FIGURKY2                       =     1; {   4 frames;   47 x   56 }
  BMP_FIGURKY                        =     2; {   4 frames;   47 x   56 }
  BMP_KOSTKA                         =     3; {   6 frames;  100 x   86 }
  BMP_LAHEV                          =     4; {   4 frames;   58 x   84 }
  BMP_LAHEVMINI                      =     5; {   4 frames;   30 x   42 }
  BMP_PLAN                           =     6; {  80 frames;   50 x   31 }
  BMP_UKAZATEL                       =     7; {  16 frames;   34 x   37 }
  BMP_GLOW                           =     8; {   1 frames;   50 x   50 }
  BMP_SELECTION                      =     9; {   3 frames;   78 x   46 }
